app_speciality_usage:
    resource: "@AppBundle/Controller/SpecialityUsageController.php"
    type:     annotation

app_speciality:
    resource: "@AppBundle/Controller/SpecialityController.php"
    type:     annotation

app_tractor_model:
    resource: "@AppBundle/Controller/TractorModelController.php"
    type:     annotation

app_implement:
    resource: "@AppBundle/Controller/ImplementController.php"
    type:     annotation

app_tractor:
    resource: "@AppBundle/Controller/TractorController.php"
    type:     annotation

app_event:
    resource: "@AppBundle/Controller/EventController.php"
    type:     annotation

app_action:
    resource: "@AppBundle/Controller/ActionController.php"
    type:     annotation

app_intervention:
    resource: "@AppBundle/Controller/InterventionController.php"
    type:     annotation

app_intervention_category:
    resource: "@AppBundle/Controller/InterventionCategoryController.php"
    type:     annotation

app_crop_cycle:
    resource: "@AppBundle/Controller/CropCycleController.php"
    type:     annotation

app_farm:
    resource: "@AppBundle/Controller/FarmController.php"
    type:     annotation

app_plot:
    resource: "@AppBundle/Controller/PlotController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
