app_farm:
    resource: "@AppBundle/Controller/FarmController.php"
    type:     annotation

app_plot:
    resource: "@AppBundle/Controller/PlotController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
