services:
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    app.registration_confirm:
        class: UserBundle\EventListener\RegistrationConfirmListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
    import.csvtoarray:
        class: AppBundle\Services\ConvertCsvToArray