services:
    app.menu.voter.request:
        class: AppBundle\Menu\RequestVoter
        arguments:
            - "@service_container"
        tags:
            - { name: knp_menu.voter }
    app.form.action:
        class: AppBundle\Form\ActionType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
