services:
    app.menu.voter.request:
        class: AppBundle\Menu\RequestVoter
        arguments:
            - "@service_container"
        tags:
            - { name: knp_menu.voter }
    app.form.action:
        class: AppBundle\Form\ActionType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
    app.form.actionfertilizer:
        class: AppBundle\Form\ActionFarmFertilizerMvtType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
    app.form.actionspeciality:
        class: AppBundle\Form\ActionFarmSpecialityMvtType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
    app.period.listener:
        class: AppBundle\EventListener\PeriodListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }